### ISSUE TITLE
Use cases for CRDT

### ISSUE THREAD

**Issue by daviddias** [ipfs/research-CRDT#1]
Similar to https://github.com/libp2p/research-pubsub/blob/master/USECASES.md, we want to collect use cases for CRDT or new use cases that are only possible with CRDTs, this will motivate the discussion of certain aspects and also its development.

**Comment by wanderer** [comment]
top two
* text editing
* chat

**Comment by diasdavid** [comment]
Text editing is happening here \o/ https://github.com/ipfs-shipyard/peerpad
Chat is happening here \o/ https://github.com/orbitdb/orbit-web

**Comment by gpestana** [comment]
Distributed forums/billboards/etc..

**Comment by RangerMauve** [comment]
Building up a distributed search index for a distributed search engine

**Comment by gpestana** [comment]
Distributed todo/task manager app - This could even be a nice 'hello world' sort of app with JSON CRDTs

**Comment by htrob** [comment]
I'm working on a collaborative knowledge-graph editing interface, currently trying to use the PubSub api, but moving data sync to a CRDT subsystem would free time for more application-specific work, doing less basic plumbing.  

It would surely accelerate application development cycles and the rate of adoption of such applications by the public.

Any chance we see any of this in go-ipfs?  
I'm working almost exclusively in Go and I'm really not fond of using the JS api at all.

If a hand is needed to make it available in Go, please let me know.
