### ISSUE TITLE
Research current CRDT implementations

### ISSUE THREAD

**Issue by daviddias** [ipfs/research-CRDT#2]
As an exercise, it would be useful to dissect CRDT implementations out there and understand its features and limitations. So far the list we have is:

- yjs
- swarmjs
- gun
- ssb
- hyperlog
- orbitdb

Please add others to this issue or PR to https://github.com/ipfs/research-CRDT#available-libraries-and-systems-using-crdt.

@pgte has volunteered to get this started.

**Comment by noffle** [comment]
Some others that are worth looking at are [hypercore](https://github.com/mafintosh/hypercore), [hyperdrive](https://github.com/mafintosh/hyperdrive) (built on hypercore), and [flume-db](https://github.com/flumedb/flumedb). They're all based on views atop of an append-only log. While not CRDTs in themselves, there's good ideas here that are directly applicable (like lightweight materialized views).

**Comment by ianopolous** [comment]
I believe I've invented a new Set CRDT that has better semantics than all known ones (in my opinion). This would also be very simple to implement. I'm surprised I can't find it in the existing literature as it seems like an obvious design. 
https://github.com/ianopolous/crdt

**Comment by haadcode** [comment]
In the IPFS world, there are:

- [ipfs-log](https://github.com/haadcode/ipfs-log), an append-only log CRDT for IPFS that is powering orbit-db and all its other CRDTs. ipfs-log itself uses a G-Set.
- orbit-db's Counter Store database uses a [G-Counter](https://github.com/haadcode/crdts/blob/master/src/G-Counter.js).

**Comment by haadcode** [comment]
Basho has been doing (I believe) pioneer work on CRDTs in [Riak](http://docs.basho.com/riak/kv/2.2.3/learn/concepts/crdts/).

**Comment by haadcode** [comment]
[Roshi](https://github.com/soundcloud/roshi) by [Soundcloud](https://developers.soundcloud.com/blog/roshi-a-crdt-system-for-timestamped-events) is for me personally a dear one not because I've used it, but because when I read their [documentation](https://github.com/soundcloud/roshi#crdt), it finally clicked and I understood what CRDTs are. And that's when I scribbled "orbit-db" literally on a napkin :)

Shout out to the devs at Soundcloud who worked on this, thank you! ❤️

**Comment by haadcode** [comment]
There are CRDTs in [Akka](http://doc.akka.io/docs/akka/snapshot/scala/distributed-data.html), started as an [experiment](https://github.com/jboner/akka-crdt) but now apparently production ready.

**Comment by haadcode** [comment]
There's an implementation for the Logoot CRDT https://github.com/usecanvas/logoot-js (I haven't looked into this yet, it's a new one for me).

**Comment by haadcode** [comment]
Almost forgot this one! [Replikativ](https://github.com/replikativ/replikativ) is written in Clojure and has [couple of CRDTs](https://github.com/replikativ/replikativ/tree/master/src/replikativ/crdt) implemented.

**Comment by diasdavid** [comment]
Another one - https://github.com/soundcloud/roshi - referenced by @lgierth

**Comment by neomodern** [comment]
[CryptPad](https://github.com/xwiki-contrib/chainpad) which uses the [ChainPad](https://github.com/xwiki-contrib/chainpad) realtime engine based on Nakamoto Blockchains.

**Comment by diasdavid** [comment]
A new CRDT impl appears 🌟 https://github.com/wehriam/ipfs-observed-remove //cc 
@wehriam

**Comment by marcoonroad** [comment]
There's [Irmin](http://github.com/mirage/irmin). While it doesn't implements CRDTs per se, it exposes an interface for user/custom CRDT implementations, and likewise, a Git backend for persistence. It is somehow in "early"/research stages of development, yet, despite its production usage in some restricted areas/fields. It's worth a reading, tho.
