### ISSUE TITLE
CRDT resources

### ISSUE THREAD

**Issue by haadcode** [ipfs/research-CRDT#3]
In addition to #2 "Research CRDT implementations", it'd be good to keep a list of resources on the topic of CRDTs. 

When I was doing the research (2015 to early 2016), it was all hard to find and scattered across the web. More importantly, a lot of great knowledge is indeed in comments on [HN](https://hn.algolia.com/?query=crdt&sort=byPopularity&prefix&page=0&dateRange=all&type=story) or [GH](https://github.com/ipfs/notes/issues/40) and digging them all out takes a lot of time and effort. It'd be good if we could keep a repo of links to such resources, blogs, discussions, etc. in order to make it easier for others in the future.

Feel free to post any and all links you find to this issue.

**Comment by haadcode** [comment]
[Resources about CRDTs and scalability](https://syncfree.lip6.fr/index.php/crdt-resources) by the [SyncFree](https://syncfree.lip6.fr/) research project (which I believe was coordinated by M. Shapiro)

**Comment by haadcode** [comment]
[Distributed systems for fun and profit - Chapter 5: Replication](http://book.mixu.net/distsys/eventual.html) has a part on CRDTs. I highly recommend to read the [full book](http://book.mixu.net/distsys/index.html) as there's plenty of golden information on distributed systems, [time and order](http://book.mixu.net/distsys/time.html), etc.

**Comment by eigendude** [comment]
There's a good compilation here: http://christophermeiklejohn.com/crdt/2014/07/22/readings-in-crdts.html

**Comment by eigendude** [comment]
and this thread has some references: https://github.com/ipfs/notes/issues/40

**Comment by lachenmayer** [comment]
@pfrazee's [CRDT notes](https://github.com/pfrazee/crdt_notes) is a great summary with the most relevant excerpts from many papers.

**Comment by haadcode** [comment]
Fresh out of research ["Pure Operation-Based Replicated Data Types"](https://arxiv.org/abs/1710.04469#)
