### ISSUE TITLE
explain the JSON-CRDT paper

### ISSUE THREAD

**Issue by pgte** [ipfs/research-CRDT#35]
Task: read [the paper](https://arxiv.org/pdf/1608.03960.pdf), resume and explain how the JSON-CRDT should work.

**Comment by pgte** [comment]
No apologies necessary, didn't come out as that.

I didn't realize there was [an internals explanation file in that repo](https://github.com/automerge/automerge/blob/master/INTERNALS.md). Is this what you were referring to? This is a good explanation, thank you!

If so, the sections "Applying operations to the local state" and "Querying the local state" are still unexplained, so perhaps this issue could work for people to complete that?

**Comment by gpestana** [comment]
The `automerge` README looks really nice, thanks for putting it together and sharing @pvh! 

@pgte how do you think it's the best way to 'explain how the JSON CRDT' works? Technical post, video, anything else ?

I think we could use the automerge documentation as a first step and add the missing parts. I like the approach in which there is code examples throughout the explanations, it makes it easy to conceptualise the ideas from the developer perspective.

**Comment by pgte** [comment]
Whatever you feel inclined to do.
I recommend either:

a) reading and expanding [the internals of automerge](https://github.com/automerge/automerge/blob/master/INTERNALS.md)
or
b) create a more abstract explanation here ([in the light of what I did for delta-CRDTs](https://github.com/ipfs/research-CRDT/issues/31))
c) use a to drive b
d) ... ?

**Comment by gpestana** [comment]
Sounds good, I will think about how to approach it. But I like the idea of expanding the internals of automerge and create a more abstract explanation with base on that.

**Comment by pvh** [comment]
Pull requests, as they say, are welcome.

**Comment by gpestana** [comment]
@pgte should this issue be closed?

**Comment by pgte** [comment]
@gpestana, yes, thank you!
Fixed via https://github.com/ipfs/research-CRDT/pull/36
Doc landed on https://github.com/ipfs/research-CRDT/blob/master/research/json-crdt.md
